### ISSUE TITLE
Individual - Results - Social Media Tie Ins 

### ISSUE THREAD

**Issue by couchpilotnye** [marcaaron/yes-on-1600#57]
Please remove the Twitter, Facebook, email and download buttons, at least for now. 

If users aren't saving or if they are against the movement, we've got concerns how negativity might spread. If it goes over well, we'll revisit. 

I'd like to get your opinion on adding our new Credo to the results page, instead of the text box we're using now. It may be too much content. 
![image](https://user-images.githubusercontent.com/37560660/38451380-b3ccabea-39e3-11e8-848e-fc981137e418.png)
Can we see if it's legible?

**Comment by dentemple** [comment]
For the Credo, it could work as an interstitial page (i.e. a page that renders prior to the expected results).

To get people to read it, though, I think we'd need to use CSS transitions to spice it up a little.  Maybe...

- Don't include the credo's header, since it'll be redundant anyway
- Break up the content into about... 4 chunks?
- Use delayed transitions on each chunk
-- 1st chunk "slides" in immediately, and then others follow in 1 second spurts from there, each of them sliding
- Give users a button to see trigger the whole thing at once

Thoughts?

Getting users to read a full page of exposition is a tough problem, if they'd, presumably, be interested in the material.  Making it dynamic could work.

**Comment by couchpilotnye** [comment]
Wow, I’m in love with this idea. If I’m picturing what you’re saying right, it could be super sweet. You’re right about the header too. It’d be a dupe. 

 

Thanks for the great input, Denny

**Comment by marcaaron** [comment]
Will comment on the credo idea shortly, but in general I'd caution against too much text or messaging in general to keep the experience short and sweet. I'd probably put any additional content after the results and make them optional. I think it's important to maybe let this be a tool that allows people to reach their own conclusions vs. having things forced on them.

I'm not sure I really understand the concern about social sharing? The whole point of this is to get people to actually use the calculator. If we can facilitate that through social sharing we should. We can't control the tone of whatever sentiment develops as a result of its use, but restricting people from sharing doesn't seem to serve us. Also there's logic in the app so that things can render differently depending on whether someone has saved. The messages populate depending on savings and no user that doesn't save would e.g. get a pre-populated tweet with say -$1,000 savings but an alternate message. Presumably if people don't save anything they wouldn't want to share those results? If people want to spread the calculator along with any negative sentiment then that could also be beneficial if they are reaching people who might follow the link and save. It's a double edged sword, but I personally think it's better to put the facts in front of people?

**Comment by couchpilotnye** [comment]
I understand concerns about too much text. The point with the credo, however, is that Universal Healthcare is much more than just a $ savings amount. It’s an entirely different world of security and freedom that’ difficult for Americans to envision. The concept of going to any doctor they want and walking out with nothing to fear financially is a big, big deal.  So if the calculator doesn’t return a Savings, they still have that. If it DOES return a Savings and they see the new world too? They may be inspired to fight. 

 

I'd probably put any additional content after the results and make them optional. Yes, definitely after the results and optional makes sense. I was just throwing it out there for ideas mostly.

 

As far as Social Media goes, again, I’d like to start without those. We don’t have a Communications team ready to respond. I want to see how it plays out on a smaller scale, give us a chance to tweak if needed, and then add them. I’m not saying I don’t ever want them. I’m saying I would like to be cautious. We’re talking people’s $ here and we’re giving them actual dollar amounts. 

 

I’d also like for us to be thinking about an appropriate disclaimer. We’re using the word ‘Estimator’ and maybe that’s enough. I’m eager to get this out there and get people excited as much as anyone. I’m also looking farther into the future and want to make sure the Savings we’re showing now aren’t used against us in some way we’re not thinking about.

**Comment by marcaaron** [comment]
Ok cool, what kind of small scale are you envisioning, can you elaborate on what that looks like? Are we talking a privately shared trial run? Or is this going to be publicly shared? If we're taking these buttons out because we're going to test the app in a closed loop then that makes sense. But if we're trying to let this spread organically and respond to user feedback that might pop up on facebook or twitter that's a different thing and we'd want to facilitate that with social sharing options. Perhaps I'm misunderstanding what the current goal is here re: user testing.

**Comment by couchpilotnye** [comment]
I’m picturing Calculator Release in phases. 

Phase 1, Approval by me, Erin, Sara

Phase 2, Review / Approval by the Working Team – about 15-20 people. 1-2 days to find anything of concern. 

Phase 3, Sent out to Whole Washington Volunteer FB Group – approx. 600 people. Give them 3 days to review and send feedback

Phase 4, Add to website

Phase 5, Add Social Media plug ins to the Calculator. Full Release to the world. 

 

This may seem overly cautious. I just want to make sure we’re prepared and it’s as smooth and positive as possible. 

 

I saw a couple small things last night. Unfortunately, I must get to work!

**Comment by couchpilotnye** [comment]
This is a great plan. Let’s do this!
		
		

		Get Outlook for iOS
	




On Tue, Apr 10, 2018 at 8:05 AM -0700, "Jen Nye" <couchpilotnye@comcast.net> wrote:












I’m picturing Calculator Release in phases. 

Phase 1, Approval by me, Erin, Sara

Phase 2, Review / Approval by the Working Team – about 15-20 people. 1-2 days to find anything of concern. 

Phase 3, Sent out to Whole Washington Volunteer FB Group – approx. 600 people. Give them 3 days to review and send feedback

Phase 4, Add to website

Phase 5, Add Social Media plug ins to the Calculator. Full Release to the world. 

 

This may seem overly cautious. I just want to make sure we’re prepared and it’s as smooth and positive as possible. 

 

I saw a couple small things last night. Unfortunately, I must get to work!

**Comment by marcaaron** [comment]
Ok! That sounds great let's do that 👍
